services:
  db:
    image: postgres:16-alpine
    container_name: gympass-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gympass
      POSTGRES_PASSWORD: gympass
      POSTGRES_DB: gympass
    ports:
      - "5432:5432"
    volumes:
      - gympass_db_data:/var/lib/postgresql/data

volumes:
  gympass_db_data:
